FROM fish/alpine-rpi

RUN echo "http://dl-3.alpinelinux.org/alpine/latest-stable/community" \
    >> /etc/apk/repositories \
    && apk add --update curl dropbear openvpn xorg-server \
       xf86-video-fbdev feh firefox xset \
    && adduser -D user

COPY  . /opt/dashboard
WORKDIR /opt/dashboard
ENTRYPOINT [ "/opt/dashboard/run" ]
