#!/bin/sh
# set -euo pipefail
set -x
URL=${URL:-https://github.com/Jodel/dashboard-viewer/blob/master/README.md#the-jodel-dashboard-viewer}

su -c "./run-user '$URL'" user &
USER_PID=$!

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

rm -rf /tmp/*

if [ -n "$REMOTE_HOST" ]; then
  cat <<EOF > /etc/openvpn.conf
client
nobind
remote-random
remote $REMOTE_HOST $REMOTE_PORT
proto tcp
mute 5
dev tun
<ca>
$( echo -e "$CERT" )
</ca>
auth-user-pass /etc/openvpn.credentials
EOF
  ( umask 0077; echo -e "${VPN_USER}\n${VPN_PASS}" > /etc/openvpn.credentials )
  openvpn --config /etc/openvpn.conf &
fi

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

dropbear -E -F
