# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1454429236);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1454431143);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.slowStartup.averageTime", 37461);
user_pref("browser.slowStartup.samples", 4);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B%7D:0.9.0.1-signed,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.5.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.5.0");
user_pref("extensions.lastPlatformVersion", "38.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}\":{\"d\":\"/root/.mozilla/firefox/rni0qukt.default/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}.xpi\",\"e\":true,\"v\":\"0.9.0.1-signed\",\"st\":1454431386000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.5.0\",\"st\":1454428552000,\"mt\":1450314979000}}}");
user_pref("gecko.buildID", "20151216080806");
user_pref("gecko.mstone", "38.5.0");
user_pref("idle.lastDailyNotification", 1454429374);
user_pref("media.gmp-manager.buildID", "20151216080806");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 12595);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1454431378);
user_pref("toolkit.telemetry.previousBuildID", "20151216080806");
user_pref("dom.max_script_run_time", 0);
